/*
 * generated by Xtext
 */
package org.xtext.senior.project;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class ProtocolRuntimeModule extends org.xtext.senior.project.AbstractProtocolRuntimeModule {

}
