
/*
 * generated by Xtext
 */
 
package org.xtext.senior.project.ui;

import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;

/**
 *@generated
 */
public class ProtocolExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return org.xtext.senior.project.ui.internal.ProtocolActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return org.xtext.senior.project.ui.internal.ProtocolActivator.getInstance().getInjector("org.xtext.senior.project.Protocol");
	}
	
}
