/*
 * generated by Xtext
 */
package org.xtext.senior.project.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class ProtocolUiModule extends org.xtext.senior.project.ui.AbstractProtocolUiModule {
	public ProtocolUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
