/*
* generated by Xtext
*/

package org.xtext.senior.project.services;

import com.google.inject.Singleton;
import com.google.inject.Inject;

import org.eclipse.xtext.*;
import org.eclipse.xtext.service.GrammarProvider;
import org.eclipse.xtext.service.AbstractElementFinder.*;

import org.eclipse.xtext.common.services.TerminalsGrammarAccess;

@Singleton
public class ProtocolGrammarAccess extends AbstractGrammarElementFinder {
	
	
	public class PDLFileElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "PDLFile");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cLeftSquareBracketKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameIDTerminalRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Keyword cRGhtSquareBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Assignment cDefinitionAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cDefinitionDefinitionsParserRuleCall_3_0 = (RuleCall)cDefinitionAssignment_3.eContents().get(0);
		private final Assignment cTransactionAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final RuleCall cTransactionTransactionsParserRuleCall_4_0 = (RuleCall)cTransactionAssignment_4.eContents().get(0);
		private final Assignment cStateAssignment_5 = (Assignment)cGroup.eContents().get(5);
		private final RuleCall cStateStatesParserRuleCall_5_0 = (RuleCall)cStateAssignment_5.eContents().get(0);
		private final Assignment cTestAssignment_6 = (Assignment)cGroup.eContents().get(6);
		private final RuleCall cTestTestParserRuleCall_6_0 = (RuleCall)cTestAssignment_6.eContents().get(0);
		private final Keyword cENDKeyword_7 = (Keyword)cGroup.eContents().get(7);
		
		//PDLFile:
		//	"[" name=ID "]" definition=Definitions transaction=Transactions state=States test=Test "[END]";
		public ParserRule getRule() { return rule; }

		//"[" name=ID "]" definition=Definitions transaction=Transactions state=States test=Test "[END]"
		public Group getGroup() { return cGroup; }

		//"["
		public Keyword getLeftSquareBracketKeyword_0() { return cLeftSquareBracketKeyword_0; }

		//name=ID
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }

		//ID
		public RuleCall getNameIDTerminalRuleCall_1_0() { return cNameIDTerminalRuleCall_1_0; }

		//"]"
		public Keyword getRGhtSquareBracketKeyword_2() { return cRGhtSquareBracketKeyword_2; }

		//definition=Definitions
		public Assignment getDefinitionAssignment_3() { return cDefinitionAssignment_3; }

		//Definitions
		public RuleCall getDefinitionDefinitionsParserRuleCall_3_0() { return cDefinitionDefinitionsParserRuleCall_3_0; }

		//transaction=Transactions
		public Assignment getTransactionAssignment_4() { return cTransactionAssignment_4; }

		//Transactions
		public RuleCall getTransactionTransactionsParserRuleCall_4_0() { return cTransactionTransactionsParserRuleCall_4_0; }

		//state=States
		public Assignment getStateAssignment_5() { return cStateAssignment_5; }

		//States
		public RuleCall getStateStatesParserRuleCall_5_0() { return cStateStatesParserRuleCall_5_0; }

		//test=Test
		public Assignment getTestAssignment_6() { return cTestAssignment_6; }

		//Test
		public RuleCall getTestTestParserRuleCall_6_0() { return cTestTestParserRuleCall_6_0; }

		//"[END]"
		public Keyword getENDKeyword_7() { return cENDKeyword_7; }
	}

	public class DefinitionsElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Definitions");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cDEFINITIONSKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cSourcesAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cSourcesEventSourceParserRuleCall_1_0 = (RuleCall)cSourcesAssignment_1.eContents().get(0);
		private final Assignment cCipherAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cCipherCipherParserRuleCall_2_0 = (RuleCall)cCipherAssignment_2.eContents().get(0);
		private final Assignment cMessageAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cMessageMessageParserRuleCall_3_0 = (RuleCall)cMessageAssignment_3.eContents().get(0);
		private final Keyword cENDKeyword_4 = (Keyword)cGroup.eContents().get(4);
		
		//Definitions:
		//	"[DEFINITIONS]" sources+=EventSource* cipher=Cipher message=Message "[END]";
		public ParserRule getRule() { return rule; }

		//"[DEFINITIONS]" sources+=EventSource* cipher=Cipher message=Message "[END]"
		public Group getGroup() { return cGroup; }

		//"[DEFINITIONS]"
		public Keyword getDEFINITIONSKeyword_0() { return cDEFINITIONSKeyword_0; }

		//sources+=EventSource*
		public Assignment getSourcesAssignment_1() { return cSourcesAssignment_1; }

		//EventSource
		public RuleCall getSourcesEventSourceParserRuleCall_1_0() { return cSourcesEventSourceParserRuleCall_1_0; }

		//cipher=Cipher
		public Assignment getCipherAssignment_2() { return cCipherAssignment_2; }

		//Cipher
		public RuleCall getCipherCipherParserRuleCall_2_0() { return cCipherCipherParserRuleCall_2_0; }

		//message=Message
		public Assignment getMessageAssignment_3() { return cMessageAssignment_3; }

		//Message
		public RuleCall getMessageMessageParserRuleCall_3_0() { return cMessageMessageParserRuleCall_3_0; }

		//"[END]"
		public Keyword getENDKeyword_4() { return cENDKeyword_4; }
	}

	public class DefineElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Define");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cEventSourceParserRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cCipherParserRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		private final RuleCall cMessageParserRuleCall_2 = (RuleCall)cAlternatives.eContents().get(2);
		
		//// Works Like Interface
		//Define:
		//	EventSource | Cipher | Message;
		public ParserRule getRule() { return rule; }

		//EventSource | Cipher | Message
		public Alternatives getAlternatives() { return cAlternatives; }

		//EventSource
		public RuleCall getEventSourceParserRuleCall_0() { return cEventSourceParserRuleCall_0; }

		//Cipher
		public RuleCall getCipherParserRuleCall_1() { return cCipherParserRuleCall_1; }

		//Message
		public RuleCall getMessageParserRuleCall_2() { return cMessageParserRuleCall_2; }
	}

	public class EventSourceElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "EventSource");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cArbitratorParserRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cParticipantParserRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		
		//EventSource:
		//	Arbitrator | Participant;
		public ParserRule getRule() { return rule; }

		//Arbitrator | Participant
		public Alternatives getAlternatives() { return cAlternatives; }

		//Arbitrator
		public RuleCall getArbitratorParserRuleCall_0() { return cArbitratorParserRuleCall_0; }

		//Participant
		public RuleCall getParticipantParserRuleCall_1() { return cParticipantParserRuleCall_1; }
	}

	public class ArbitratorElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Arbitrator");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cNameAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final RuleCall cNameIDTerminalRuleCall_0_0 = (RuleCall)cNameAssignment_0.eContents().get(0);
		private final Keyword cEqualsSGnKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cKeywordAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final Keyword cKeywordArbitratorKeyword_2_0 = (Keyword)cKeywordAssignment_2.eContents().get(0);
		
		//Arbitrator:
		//	name=ID "=" keyword="Arbitrator";
		public ParserRule getRule() { return rule; }

		//name=ID "=" keyword="Arbitrator"
		public Group getGroup() { return cGroup; }

		//name=ID
		public Assignment getNameAssignment_0() { return cNameAssignment_0; }

		//ID
		public RuleCall getNameIDTerminalRuleCall_0_0() { return cNameIDTerminalRuleCall_0_0; }

		//"="
		public Keyword getEqualsSGnKeyword_1() { return cEqualsSGnKeyword_1; }

		//keyword="Arbitrator"
		public Assignment getKeywordAssignment_2() { return cKeywordAssignment_2; }

		//"Arbitrator"
		public Keyword getKeywordArbitratorKeyword_2_0() { return cKeywordArbitratorKeyword_2_0; }
	}

	public class ParticipantElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Participant");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cNameAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final RuleCall cNameIDTerminalRuleCall_0_0 = (RuleCall)cNameAssignment_0.eContents().get(0);
		private final Keyword cEqualsSGnKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cKeywordAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final Keyword cKeywordParticipantKeyword_2_0 = (Keyword)cKeywordAssignment_2.eContents().get(0);
		
		//Participant:
		//	name=ID "=" keyword="Participant";
		public ParserRule getRule() { return rule; }

		//name=ID "=" keyword="Participant"
		public Group getGroup() { return cGroup; }

		//name=ID
		public Assignment getNameAssignment_0() { return cNameAssignment_0; }

		//ID
		public RuleCall getNameIDTerminalRuleCall_0_0() { return cNameIDTerminalRuleCall_0_0; }

		//"="
		public Keyword getEqualsSGnKeyword_1() { return cEqualsSGnKeyword_1; }

		//keyword="Participant"
		public Assignment getKeywordAssignment_2() { return cKeywordAssignment_2; }

		//"Participant"
		public Keyword getKeywordParticipantKeyword_2_0() { return cKeywordParticipantKeyword_2_0; }
	}

	public class CipherElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Cipher");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cNameAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final RuleCall cNameIDTerminalRuleCall_0_0 = (RuleCall)cNameAssignment_0.eContents().get(0);
		private final Keyword cEqualsSGnKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cKeywordAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final Alternatives cKeywordAlternatives_2_0 = (Alternatives)cKeywordAssignment_2.eContents().get(0);
		private final Keyword cKeywordAsynchronousCipherKeyword_2_0_0 = (Keyword)cKeywordAlternatives_2_0.eContents().get(0);
		private final Keyword cKeywordSynchronousCipherKeyword_2_0_1 = (Keyword)cKeywordAlternatives_2_0.eContents().get(1);
		
		//Cipher:
		//	name=ID "=" keyword=("AsynchronousCipher" | "SynchronousCipher");
		public ParserRule getRule() { return rule; }

		//name=ID "=" keyword=("AsynchronousCipher" | "SynchronousCipher")
		public Group getGroup() { return cGroup; }

		//name=ID
		public Assignment getNameAssignment_0() { return cNameAssignment_0; }

		//ID
		public RuleCall getNameIDTerminalRuleCall_0_0() { return cNameIDTerminalRuleCall_0_0; }

		//"="
		public Keyword getEqualsSGnKeyword_1() { return cEqualsSGnKeyword_1; }

		//keyword=("AsynchronousCipher" | "SynchronousCipher")
		public Assignment getKeywordAssignment_2() { return cKeywordAssignment_2; }

		//"AsynchronousCipher" | "SynchronousCipher"
		public Alternatives getKeywordAlternatives_2_0() { return cKeywordAlternatives_2_0; }

		//"AsynchronousCipher"
		public Keyword getKeywordAsynchronousCipherKeyword_2_0_0() { return cKeywordAsynchronousCipherKeyword_2_0_0; }

		//"SynchronousCipher"
		public Keyword getKeywordSynchronousCipherKeyword_2_0_1() { return cKeywordSynchronousCipherKeyword_2_0_1; }
	}

	public class MessageElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Message");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cNameAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final RuleCall cNameIDTerminalRuleCall_0_0 = (RuleCall)cNameAssignment_0.eContents().get(0);
		private final Keyword cEqualsSGnKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cKeywordAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final Keyword cKeywordMessageKeyword_2_0 = (Keyword)cKeywordAssignment_2.eContents().get(0);
		
		//Message:
		//	name=ID "=" keyword="Message";
		public ParserRule getRule() { return rule; }

		//name=ID "=" keyword="Message"
		public Group getGroup() { return cGroup; }

		//name=ID
		public Assignment getNameAssignment_0() { return cNameAssignment_0; }

		//ID
		public RuleCall getNameIDTerminalRuleCall_0_0() { return cNameIDTerminalRuleCall_0_0; }

		//"="
		public Keyword getEqualsSGnKeyword_1() { return cEqualsSGnKeyword_1; }

		//keyword="Message"
		public Assignment getKeywordAssignment_2() { return cKeywordAssignment_2; }

		//"Message"
		public Keyword getKeywordMessageKeyword_2_0() { return cKeywordMessageKeyword_2_0; }
	}

	public class KeywordElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Keyword");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final Keyword cArbitratorKeyword_0 = (Keyword)cAlternatives.eContents().get(0);
		private final Keyword cParticipantKeyword_1 = (Keyword)cAlternatives.eContents().get(1);
		private final Keyword cMessageKeyword_2 = (Keyword)cAlternatives.eContents().get(2);
		private final Keyword cAsynchronousCipherKeyword_3 = (Keyword)cAlternatives.eContents().get(3);
		private final Keyword cSynchronousCipherKeyword_4 = (Keyword)cAlternatives.eContents().get(4);
		
		//Keyword returns ecore::EString:
		//	"Arbitrator" | "Participant" | "Message" | "AsynchronousCipher" | "SynchronousCipher";
		public ParserRule getRule() { return rule; }

		//"Arbitrator" | "Participant" | "Message" | "AsynchronousCipher" | "SynchronousCipher"
		public Alternatives getAlternatives() { return cAlternatives; }

		//"Arbitrator"
		public Keyword getArbitratorKeyword_0() { return cArbitratorKeyword_0; }

		//"Participant"
		public Keyword getParticipantKeyword_1() { return cParticipantKeyword_1; }

		//"Message"
		public Keyword getMessageKeyword_2() { return cMessageKeyword_2; }

		//"AsynchronousCipher"
		public Keyword getAsynchronousCipherKeyword_3() { return cAsynchronousCipherKeyword_3; }

		//"SynchronousCipher"
		public Keyword getSynchronousCipherKeyword_4() { return cSynchronousCipherKeyword_4; }
	}

	public class TransactionsElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Transactions");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cTRANSACTIONSKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cTransactionsAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cTransactionsTransactionParserRuleCall_1_0 = (RuleCall)cTransactionsAssignment_1.eContents().get(0);
		private final Keyword cENDKeyword_2 = (Keyword)cGroup.eContents().get(2);
		
		//Transactions:
		//	"[TRANSACTIONS]" transactions+=Transaction* "[END]";
		public ParserRule getRule() { return rule; }

		//"[TRANSACTIONS]" transactions+=Transaction* "[END]"
		public Group getGroup() { return cGroup; }

		//"[TRANSACTIONS]"
		public Keyword getTRANSACTIONSKeyword_0() { return cTRANSACTIONSKeyword_0; }

		//transactions+=Transaction*
		public Assignment getTransactionsAssignment_1() { return cTransactionsAssignment_1; }

		//Transaction
		public RuleCall getTransactionsTransactionParserRuleCall_1_0() { return cTransactionsTransactionParserRuleCall_1_0; }

		//"[END]"
		public Keyword getENDKeyword_2() { return cENDKeyword_2; }
	}

	public class TransactionElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Transaction");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cTRANSACTIONKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameIDTerminalRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Keyword cLeftParenthesSKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Assignment cArgumentsAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cArgumentsArgumentParserRuleCall_3_0 = (RuleCall)cArgumentsAssignment_3.eContents().get(0);
		private final Keyword cRGhtParenthesSKeyword_4 = (Keyword)cGroup.eContents().get(4);
		private final Keyword cBEGINKeyword_5 = (Keyword)cGroup.eContents().get(5);
		private final Assignment cOperationsAssignment_6 = (Assignment)cGroup.eContents().get(6);
		private final RuleCall cOperationsOperationParserRuleCall_6_0 = (RuleCall)cOperationsAssignment_6.eContents().get(0);
		private final Keyword cENDKeyword_7 = (Keyword)cGroup.eContents().get(7);
		
		//Transaction:
		//	"TRANSACTION" name=ID "(" arguments+=Argument* ")" "[BEGIN]" operations+=Operation* "[END]";
		public ParserRule getRule() { return rule; }

		//"TRANSACTION" name=ID "(" arguments+=Argument* ")" "[BEGIN]" operations+=Operation* "[END]"
		public Group getGroup() { return cGroup; }

		//"TRANSACTION"
		public Keyword getTRANSACTIONKeyword_0() { return cTRANSACTIONKeyword_0; }

		//name=ID
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }

		//ID
		public RuleCall getNameIDTerminalRuleCall_1_0() { return cNameIDTerminalRuleCall_1_0; }

		//"("
		public Keyword getLeftParenthesSKeyword_2() { return cLeftParenthesSKeyword_2; }

		//arguments+=Argument*
		public Assignment getArgumentsAssignment_3() { return cArgumentsAssignment_3; }

		//Argument
		public RuleCall getArgumentsArgumentParserRuleCall_3_0() { return cArgumentsArgumentParserRuleCall_3_0; }

		//")"
		public Keyword getRGhtParenthesSKeyword_4() { return cRGhtParenthesSKeyword_4; }

		//"[BEGIN]"
		public Keyword getBEGINKeyword_5() { return cBEGINKeyword_5; }

		//operations+=Operation*
		public Assignment getOperationsAssignment_6() { return cOperationsAssignment_6; }

		//Operation
		public RuleCall getOperationsOperationParserRuleCall_6_0() { return cOperationsOperationParserRuleCall_6_0; }

		//"[END]"
		public Keyword getENDKeyword_7() { return cENDKeyword_7; }
	}

	public class ArgumentElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Argument");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cKeywordAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final RuleCall cKeywordKeywordParserRuleCall_0_0 = (RuleCall)cKeywordAssignment_0.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameIDTerminalRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		
		//Argument:
		//	keyword=Keyword name=ID;
		public ParserRule getRule() { return rule; }

		//keyword=Keyword name=ID
		public Group getGroup() { return cGroup; }

		//keyword=Keyword
		public Assignment getKeywordAssignment_0() { return cKeywordAssignment_0; }

		//Keyword
		public RuleCall getKeywordKeywordParserRuleCall_0_0() { return cKeywordKeywordParserRuleCall_0_0; }

		//name=ID
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }

		//ID
		public RuleCall getNameIDTerminalRuleCall_1_0() { return cNameIDTerminalRuleCall_1_0; }
	}

	public class OperationElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Operation");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cDecryptParserRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cEncryptParserRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		private final RuleCall cSendParserRuleCall_2 = (RuleCall)cAlternatives.eContents().get(2);
		private final RuleCall cPrintParserRuleCall_3 = (RuleCall)cAlternatives.eContents().get(3);
		private final RuleCall cCallParserRuleCall_4 = (RuleCall)cAlternatives.eContents().get(4);
		private final RuleCall cExchangeParserRuleCall_5 = (RuleCall)cAlternatives.eContents().get(5);
		private final RuleCall cRedirectParserRuleCall_6 = (RuleCall)cAlternatives.eContents().get(6);
		
		//Operation:
		//	Decrypt | Encrypt | Send | Print | Call | Exchange | Redirect;
		public ParserRule getRule() { return rule; }

		//Decrypt | Encrypt | Send | Print | Call | Exchange | Redirect
		public Alternatives getAlternatives() { return cAlternatives; }

		//Decrypt
		public RuleCall getDecryptParserRuleCall_0() { return cDecryptParserRuleCall_0; }

		//Encrypt
		public RuleCall getEncryptParserRuleCall_1() { return cEncryptParserRuleCall_1; }

		//Send
		public RuleCall getSendParserRuleCall_2() { return cSendParserRuleCall_2; }

		//Print
		public RuleCall getPrintParserRuleCall_3() { return cPrintParserRuleCall_3; }

		//Call
		public RuleCall getCallParserRuleCall_4() { return cCallParserRuleCall_4; }

		//Exchange
		public RuleCall getExchangeParserRuleCall_5() { return cExchangeParserRuleCall_5; }

		//Redirect
		public RuleCall getRedirectParserRuleCall_6() { return cRedirectParserRuleCall_6; }
	}

	public class DecryptElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Decrypt");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cDecryptKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cMessageAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cMessageIDTerminalRuleCall_1_0 = (RuleCall)cMessageAssignment_1.eContents().get(0);
		private final Keyword cForKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Assignment cParticipantAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final CrossReference cParticipantParticipantCrossReference_3_0 = (CrossReference)cParticipantAssignment_3.eContents().get(0);
		private final RuleCall cParticipantParticipantIDTerminalRuleCall_3_0_1 = (RuleCall)cParticipantParticipantCrossReference_3_0.eContents().get(1);
		
		//Decrypt:
		//	"decrypt" message=ID "for" participant=[Participant];
		public ParserRule getRule() { return rule; }

		//"decrypt" message=ID "for" participant=[Participant]
		public Group getGroup() { return cGroup; }

		//"decrypt"
		public Keyword getDecryptKeyword_0() { return cDecryptKeyword_0; }

		//message=ID
		public Assignment getMessageAssignment_1() { return cMessageAssignment_1; }

		//ID
		public RuleCall getMessageIDTerminalRuleCall_1_0() { return cMessageIDTerminalRuleCall_1_0; }

		//"for"
		public Keyword getForKeyword_2() { return cForKeyword_2; }

		//participant=[Participant]
		public Assignment getParticipantAssignment_3() { return cParticipantAssignment_3; }

		//[Participant]
		public CrossReference getParticipantParticipantCrossReference_3_0() { return cParticipantParticipantCrossReference_3_0; }

		//ID
		public RuleCall getParticipantParticipantIDTerminalRuleCall_3_0_1() { return cParticipantParticipantIDTerminalRuleCall_3_0_1; }
	}

	public class EncryptElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Encrypt");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cEncryptKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cMessageAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cMessageIDTerminalRuleCall_1_0 = (RuleCall)cMessageAssignment_1.eContents().get(0);
		private final Keyword cForKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Assignment cParticipantAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final CrossReference cParticipantParticipantCrossReference_3_0 = (CrossReference)cParticipantAssignment_3.eContents().get(0);
		private final RuleCall cParticipantParticipantIDTerminalRuleCall_3_0_1 = (RuleCall)cParticipantParticipantCrossReference_3_0.eContents().get(1);
		
		//Encrypt:
		//	"encrypt" message=ID "for" participant=[Participant];
		public ParserRule getRule() { return rule; }

		//"encrypt" message=ID "for" participant=[Participant]
		public Group getGroup() { return cGroup; }

		//"encrypt"
		public Keyword getEncryptKeyword_0() { return cEncryptKeyword_0; }

		//message=ID
		public Assignment getMessageAssignment_1() { return cMessageAssignment_1; }

		//ID
		public RuleCall getMessageIDTerminalRuleCall_1_0() { return cMessageIDTerminalRuleCall_1_0; }

		//"for"
		public Keyword getForKeyword_2() { return cForKeyword_2; }

		//participant=[Participant]
		public Assignment getParticipantAssignment_3() { return cParticipantAssignment_3; }

		//[Participant]
		public CrossReference getParticipantParticipantCrossReference_3_0() { return cParticipantParticipantCrossReference_3_0; }

		//ID
		public RuleCall getParticipantParticipantIDTerminalRuleCall_3_0_1() { return cParticipantParticipantIDTerminalRuleCall_3_0_1; }
	}

	public class SendElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Send");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cMessageAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final RuleCall cMessageIDTerminalRuleCall_0_0 = (RuleCall)cMessageAssignment_0.eContents().get(0);
		private final Keyword cColonColonKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cSourceAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final CrossReference cSourceEventSourceCrossReference_2_0 = (CrossReference)cSourceAssignment_2.eContents().get(0);
		private final RuleCall cSourceEventSourceIDTerminalRuleCall_2_0_1 = (RuleCall)cSourceEventSourceCrossReference_2_0.eContents().get(1);
		private final Keyword cHyphenMNusGreaterThanSGnKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Assignment cDestinationAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final CrossReference cDestinationEventSourceCrossReference_4_0 = (CrossReference)cDestinationAssignment_4.eContents().get(0);
		private final RuleCall cDestinationEventSourceIDTerminalRuleCall_4_0_1 = (RuleCall)cDestinationEventSourceCrossReference_4_0.eContents().get(1);
		
		//Send:
		//	message=ID "::" source=[EventSource] "->" destination=[EventSource];
		public ParserRule getRule() { return rule; }

		//message=ID "::" source=[EventSource] "->" destination=[EventSource]
		public Group getGroup() { return cGroup; }

		//message=ID
		public Assignment getMessageAssignment_0() { return cMessageAssignment_0; }

		//ID
		public RuleCall getMessageIDTerminalRuleCall_0_0() { return cMessageIDTerminalRuleCall_0_0; }

		//"::"
		public Keyword getColonColonKeyword_1() { return cColonColonKeyword_1; }

		//source=[EventSource]
		public Assignment getSourceAssignment_2() { return cSourceAssignment_2; }

		//[EventSource]
		public CrossReference getSourceEventSourceCrossReference_2_0() { return cSourceEventSourceCrossReference_2_0; }

		//ID
		public RuleCall getSourceEventSourceIDTerminalRuleCall_2_0_1() { return cSourceEventSourceIDTerminalRuleCall_2_0_1; }

		//"->"
		public Keyword getHyphenMNusGreaterThanSGnKeyword_3() { return cHyphenMNusGreaterThanSGnKeyword_3; }

		//destination=[EventSource]
		public Assignment getDestinationAssignment_4() { return cDestinationAssignment_4; }

		//[EventSource]
		public CrossReference getDestinationEventSourceCrossReference_4_0() { return cDestinationEventSourceCrossReference_4_0; }

		//ID
		public RuleCall getDestinationEventSourceIDTerminalRuleCall_4_0_1() { return cDestinationEventSourceIDTerminalRuleCall_4_0_1; }
	}

	public class PrintElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Print");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cPrintKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cMessageAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cMessageIDTerminalRuleCall_1_0 = (RuleCall)cMessageAssignment_1.eContents().get(0);
		
		//Print:
		//	"print" message=ID;
		public ParserRule getRule() { return rule; }

		//"print" message=ID
		public Group getGroup() { return cGroup; }

		//"print"
		public Keyword getPrintKeyword_0() { return cPrintKeyword_0; }

		//message=ID
		public Assignment getMessageAssignment_1() { return cMessageAssignment_1; }

		//ID
		public RuleCall getMessageIDTerminalRuleCall_1_0() { return cMessageIDTerminalRuleCall_1_0; }
	}

	public class CallElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Call");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cCALLKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cTransactionNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final CrossReference cTransactionNameTransactionCrossReference_1_0 = (CrossReference)cTransactionNameAssignment_1.eContents().get(0);
		private final RuleCall cTransactionNameTransactionIDTerminalRuleCall_1_0_1 = (RuleCall)cTransactionNameTransactionCrossReference_1_0.eContents().get(1);
		private final Keyword cLeftParenthesSKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Assignment cArgsAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final CrossReference cArgsDefineCrossReference_3_0 = (CrossReference)cArgsAssignment_3.eContents().get(0);
		private final RuleCall cArgsDefineIDTerminalRuleCall_3_0_1 = (RuleCall)cArgsDefineCrossReference_3_0.eContents().get(1);
		private final Keyword cRGhtParenthesSKeyword_4 = (Keyword)cGroup.eContents().get(4);
		
		//Call:
		//	"CALL" transactionName=[Transaction] "(" args+=[Define]* ")";
		public ParserRule getRule() { return rule; }

		//"CALL" transactionName=[Transaction] "(" args+=[Define]* ")"
		public Group getGroup() { return cGroup; }

		//"CALL"
		public Keyword getCALLKeyword_0() { return cCALLKeyword_0; }

		//transactionName=[Transaction]
		public Assignment getTransactionNameAssignment_1() { return cTransactionNameAssignment_1; }

		//[Transaction]
		public CrossReference getTransactionNameTransactionCrossReference_1_0() { return cTransactionNameTransactionCrossReference_1_0; }

		//ID
		public RuleCall getTransactionNameTransactionIDTerminalRuleCall_1_0_1() { return cTransactionNameTransactionIDTerminalRuleCall_1_0_1; }

		//"("
		public Keyword getLeftParenthesSKeyword_2() { return cLeftParenthesSKeyword_2; }

		//args+=[Define]*
		public Assignment getArgsAssignment_3() { return cArgsAssignment_3; }

		//[Define]
		public CrossReference getArgsDefineCrossReference_3_0() { return cArgsDefineCrossReference_3_0; }

		//ID
		public RuleCall getArgsDefineIDTerminalRuleCall_3_0_1() { return cArgsDefineIDTerminalRuleCall_3_0_1; }

		//")"
		public Keyword getRGhtParenthesSKeyword_4() { return cRGhtParenthesSKeyword_4; }
	}

	public class ExchangeElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Exchange");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cSourceAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final CrossReference cSourceEventSourceCrossReference_0_0 = (CrossReference)cSourceAssignment_0.eContents().get(0);
		private final RuleCall cSourceEventSourceIDTerminalRuleCall_0_0_1 = (RuleCall)cSourceEventSourceCrossReference_0_0.eContents().get(1);
		private final Keyword cExchangeKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cDestinationAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final CrossReference cDestinationEventSourceCrossReference_2_0 = (CrossReference)cDestinationAssignment_2.eContents().get(0);
		private final RuleCall cDestinationEventSourceIDTerminalRuleCall_2_0_1 = (RuleCall)cDestinationEventSourceCrossReference_2_0.eContents().get(1);
		
		//Exchange:
		//	source=[EventSource] "exchange" destination=[EventSource];
		public ParserRule getRule() { return rule; }

		//source=[EventSource] "exchange" destination=[EventSource]
		public Group getGroup() { return cGroup; }

		//source=[EventSource]
		public Assignment getSourceAssignment_0() { return cSourceAssignment_0; }

		//[EventSource]
		public CrossReference getSourceEventSourceCrossReference_0_0() { return cSourceEventSourceCrossReference_0_0; }

		//ID
		public RuleCall getSourceEventSourceIDTerminalRuleCall_0_0_1() { return cSourceEventSourceIDTerminalRuleCall_0_0_1; }

		//"exchange"
		public Keyword getExchangeKeyword_1() { return cExchangeKeyword_1; }

		//destination=[EventSource]
		public Assignment getDestinationAssignment_2() { return cDestinationAssignment_2; }

		//[EventSource]
		public CrossReference getDestinationEventSourceCrossReference_2_0() { return cDestinationEventSourceCrossReference_2_0; }

		//ID
		public RuleCall getDestinationEventSourceIDTerminalRuleCall_2_0_1() { return cDestinationEventSourceIDTerminalRuleCall_2_0_1; }
	}

	public class RedirectElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Redirect");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cMessageAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final RuleCall cMessageIDTerminalRuleCall_0_0 = (RuleCall)cMessageAssignment_0.eContents().get(0);
		private final Keyword cRedirectKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cDestinationAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final CrossReference cDestinationEventSourceCrossReference_2_0 = (CrossReference)cDestinationAssignment_2.eContents().get(0);
		private final RuleCall cDestinationEventSourceIDTerminalRuleCall_2_0_1 = (RuleCall)cDestinationEventSourceCrossReference_2_0.eContents().get(1);
		
		//Redirect:
		//	message=ID "redirect" destination=[EventSource];
		public ParserRule getRule() { return rule; }

		//message=ID "redirect" destination=[EventSource]
		public Group getGroup() { return cGroup; }

		//message=ID
		public Assignment getMessageAssignment_0() { return cMessageAssignment_0; }

		//ID
		public RuleCall getMessageIDTerminalRuleCall_0_0() { return cMessageIDTerminalRuleCall_0_0; }

		//"redirect"
		public Keyword getRedirectKeyword_1() { return cRedirectKeyword_1; }

		//destination=[EventSource]
		public Assignment getDestinationAssignment_2() { return cDestinationAssignment_2; }

		//[EventSource]
		public CrossReference getDestinationEventSourceCrossReference_2_0() { return cDestinationEventSourceCrossReference_2_0; }

		//ID
		public RuleCall getDestinationEventSourceIDTerminalRuleCall_2_0_1() { return cDestinationEventSourceIDTerminalRuleCall_2_0_1; }
	}

	public class StatesElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "States");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cSTATESKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cStatesAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cStatesStateParserRuleCall_1_0 = (RuleCall)cStatesAssignment_1.eContents().get(0);
		private final Keyword cENDKeyword_2 = (Keyword)cGroup.eContents().get(2);
		
		//States:
		//	"[STATES]" states+=State* "[END]";
		public ParserRule getRule() { return rule; }

		//"[STATES]" states+=State* "[END]"
		public Group getGroup() { return cGroup; }

		//"[STATES]"
		public Keyword getSTATESKeyword_0() { return cSTATESKeyword_0; }

		//states+=State*
		public Assignment getStatesAssignment_1() { return cStatesAssignment_1; }

		//State
		public RuleCall getStatesStateParserRuleCall_1_0() { return cStatesStateParserRuleCall_1_0; }

		//"[END]"
		public Keyword getENDKeyword_2() { return cENDKeyword_2; }
	}

	public class StateElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "State");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cSTATEKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameIDTerminalRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Keyword cLeftParenthesSKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Assignment cEventAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cEventEventParserRuleCall_3_0 = (RuleCall)cEventAssignment_3.eContents().get(0);
		private final Keyword cRGhtParenthesSKeyword_4 = (Keyword)cGroup.eContents().get(4);
		private final Keyword cBEGINKeyword_5 = (Keyword)cGroup.eContents().get(5);
		private final Assignment cGuardsAssignment_6 = (Assignment)cGroup.eContents().get(6);
		private final RuleCall cGuardsGuardParserRuleCall_6_0 = (RuleCall)cGuardsAssignment_6.eContents().get(0);
		private final Keyword cENDKeyword_7 = (Keyword)cGroup.eContents().get(7);
		
		//State:
		//	"STATE" name=ID "(" event=Event ")" "[BEGIN]" guards+=Guard* "[END]";
		public ParserRule getRule() { return rule; }

		//"STATE" name=ID "(" event=Event ")" "[BEGIN]" guards+=Guard* "[END]"
		public Group getGroup() { return cGroup; }

		//"STATE"
		public Keyword getSTATEKeyword_0() { return cSTATEKeyword_0; }

		//name=ID
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }

		//ID
		public RuleCall getNameIDTerminalRuleCall_1_0() { return cNameIDTerminalRuleCall_1_0; }

		//"("
		public Keyword getLeftParenthesSKeyword_2() { return cLeftParenthesSKeyword_2; }

		//event=Event
		public Assignment getEventAssignment_3() { return cEventAssignment_3; }

		//Event
		public RuleCall getEventEventParserRuleCall_3_0() { return cEventEventParserRuleCall_3_0; }

		//")"
		public Keyword getRGhtParenthesSKeyword_4() { return cRGhtParenthesSKeyword_4; }

		//"[BEGIN]"
		public Keyword getBEGINKeyword_5() { return cBEGINKeyword_5; }

		//guards+=Guard*
		public Assignment getGuardsAssignment_6() { return cGuardsAssignment_6; }

		//Guard
		public RuleCall getGuardsGuardParserRuleCall_6_0() { return cGuardsGuardParserRuleCall_6_0; }

		//"[END]"
		public Keyword getENDKeyword_7() { return cENDKeyword_7; }
	}

	public class GuardElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Guard");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cVertCalLNeKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cCasemAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cCasemCaseParserRuleCall_1_0 = (RuleCall)cCasemAssignment_1.eContents().get(0);
		private final Keyword cEqualsSGnGreaterThanSGnKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Assignment cOperationAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cOperationOperationParserRuleCall_3_0 = (RuleCall)cOperationAssignment_3.eContents().get(0);
		
		//Guard:
		//	"|" casem=Case "=>" operation=Operation;
		public ParserRule getRule() { return rule; }

		//"|" casem=Case "=>" operation=Operation
		public Group getGroup() { return cGroup; }

		//"|"
		public Keyword getVertCalLNeKeyword_0() { return cVertCalLNeKeyword_0; }

		//casem=Case
		public Assignment getCasemAssignment_1() { return cCasemAssignment_1; }

		//Case
		public RuleCall getCasemCaseParserRuleCall_1_0() { return cCasemCaseParserRuleCall_1_0; }

		//"=>"
		public Keyword getEqualsSGnGreaterThanSGnKeyword_2() { return cEqualsSGnGreaterThanSGnKeyword_2; }

		//operation=Operation
		public Assignment getOperationAssignment_3() { return cOperationAssignment_3; }

		//Operation
		public RuleCall getOperationOperationParserRuleCall_3_0() { return cOperationOperationParserRuleCall_3_0; }
	}

	public class EventElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Event");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cGetEventParserRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cIsSendEventParserRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		private final RuleCall cInitParserRuleCall_2 = (RuleCall)cAlternatives.eContents().get(2);
		private final RuleCall cSendsEventParserRuleCall_3 = (RuleCall)cAlternatives.eContents().get(3);
		
		//Event:
		//	GetEvent | IsSendEvent | Init | SendsEvent;
		public ParserRule getRule() { return rule; }

		//GetEvent | IsSendEvent | Init | SendsEvent
		public Alternatives getAlternatives() { return cAlternatives; }

		//GetEvent
		public RuleCall getGetEventParserRuleCall_0() { return cGetEventParserRuleCall_0; }

		//IsSendEvent
		public RuleCall getIsSendEventParserRuleCall_1() { return cIsSendEventParserRuleCall_1; }

		//Init
		public RuleCall getInitParserRuleCall_2() { return cInitParserRuleCall_2; }

		//SendsEvent
		public RuleCall getSendsEventParserRuleCall_3() { return cSendsEventParserRuleCall_3; }
	}

	public class GetEventElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "GetEvent");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cWhoAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final CrossReference cWhoDefineCrossReference_0_0 = (CrossReference)cWhoAssignment_0.eContents().get(0);
		private final RuleCall cWhoDefineIDTerminalRuleCall_0_0_1 = (RuleCall)cWhoDefineCrossReference_0_0.eContents().get(1);
		private final Keyword cGETKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cMessageAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final CrossReference cMessageMessageCrossReference_2_0 = (CrossReference)cMessageAssignment_2.eContents().get(0);
		private final RuleCall cMessageMessageIDTerminalRuleCall_2_0_1 = (RuleCall)cMessageMessageCrossReference_2_0.eContents().get(1);
		
		//GetEvent:
		//	who=[Define] "GET" message=[Message];
		public ParserRule getRule() { return rule; }

		//who=[Define] "GET" message=[Message]
		public Group getGroup() { return cGroup; }

		//who=[Define]
		public Assignment getWhoAssignment_0() { return cWhoAssignment_0; }

		//[Define]
		public CrossReference getWhoDefineCrossReference_0_0() { return cWhoDefineCrossReference_0_0; }

		//ID
		public RuleCall getWhoDefineIDTerminalRuleCall_0_0_1() { return cWhoDefineIDTerminalRuleCall_0_0_1; }

		//"GET"
		public Keyword getGETKeyword_1() { return cGETKeyword_1; }

		//message=[Message]
		public Assignment getMessageAssignment_2() { return cMessageAssignment_2; }

		//[Message]
		public CrossReference getMessageMessageCrossReference_2_0() { return cMessageMessageCrossReference_2_0; }

		//ID
		public RuleCall getMessageMessageIDTerminalRuleCall_2_0_1() { return cMessageMessageIDTerminalRuleCall_2_0_1; }
	}

	public class SendsEventElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "SendsEvent");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cWhoAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final CrossReference cWhoDefineCrossReference_0_0 = (CrossReference)cWhoAssignment_0.eContents().get(0);
		private final RuleCall cWhoDefineIDTerminalRuleCall_0_0_1 = (RuleCall)cWhoDefineCrossReference_0_0.eContents().get(1);
		private final Keyword cSENDSKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cMessageAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final CrossReference cMessageMessageCrossReference_2_0 = (CrossReference)cMessageAssignment_2.eContents().get(0);
		private final RuleCall cMessageMessageIDTerminalRuleCall_2_0_1 = (RuleCall)cMessageMessageCrossReference_2_0.eContents().get(1);
		
		//SendsEvent:
		//	who=[Define] "SENDS" message=[Message];
		public ParserRule getRule() { return rule; }

		//who=[Define] "SENDS" message=[Message]
		public Group getGroup() { return cGroup; }

		//who=[Define]
		public Assignment getWhoAssignment_0() { return cWhoAssignment_0; }

		//[Define]
		public CrossReference getWhoDefineCrossReference_0_0() { return cWhoDefineCrossReference_0_0; }

		//ID
		public RuleCall getWhoDefineIDTerminalRuleCall_0_0_1() { return cWhoDefineIDTerminalRuleCall_0_0_1; }

		//"SENDS"
		public Keyword getSENDSKeyword_1() { return cSENDSKeyword_1; }

		//message=[Message]
		public Assignment getMessageAssignment_2() { return cMessageAssignment_2; }

		//[Message]
		public CrossReference getMessageMessageCrossReference_2_0() { return cMessageMessageCrossReference_2_0; }

		//ID
		public RuleCall getMessageMessageIDTerminalRuleCall_2_0_1() { return cMessageMessageIDTerminalRuleCall_2_0_1; }
	}

	public class IsSendEventElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "IsSendEvent");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cMessageAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final CrossReference cMessageMessageCrossReference_0_0 = (CrossReference)cMessageAssignment_0.eContents().get(0);
		private final RuleCall cMessageMessageIDTerminalRuleCall_0_0_1 = (RuleCall)cMessageMessageCrossReference_0_0.eContents().get(1);
		private final Keyword cIS_SENDKeyword_1 = (Keyword)cGroup.eContents().get(1);
		
		//IsSendEvent:
		//	message=[Message] "IS_SEND";
		public ParserRule getRule() { return rule; }

		//message=[Message] "IS_SEND"
		public Group getGroup() { return cGroup; }

		//message=[Message]
		public Assignment getMessageAssignment_0() { return cMessageAssignment_0; }

		//[Message]
		public CrossReference getMessageMessageCrossReference_0_0() { return cMessageMessageCrossReference_0_0; }

		//ID
		public RuleCall getMessageMessageIDTerminalRuleCall_0_0_1() { return cMessageMessageIDTerminalRuleCall_0_0_1; }

		//"IS_SEND"
		public Keyword getIS_SENDKeyword_1() { return cIS_SENDKeyword_1; }
	}

	public class InitElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Init");
		private final Assignment cKeywordAssignment = (Assignment)rule.eContents().get(1);
		private final Keyword cKeywordINITKeyword_0 = (Keyword)cKeywordAssignment.eContents().get(0);
		
		//Init:
		//	keyword="INIT";
		public ParserRule getRule() { return rule; }

		//keyword="INIT"
		public Assignment getKeywordAssignment() { return cKeywordAssignment; }

		//"INIT"
		public Keyword getKeywordINITKeyword_0() { return cKeywordINITKeyword_0; }
	}

	public class CaseElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Case");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cAlwaysParserRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cOtherwiseParserRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		private final RuleCall cToParserRuleCall_2 = (RuleCall)cAlternatives.eContents().get(2);
		private final RuleCall cFromParserRuleCall_3 = (RuleCall)cAlternatives.eContents().get(3);
		
		//Case:
		//	Always | Otherwise | To | From;
		public ParserRule getRule() { return rule; }

		//Always | Otherwise | To | From
		public Alternatives getAlternatives() { return cAlternatives; }

		//Always
		public RuleCall getAlwaysParserRuleCall_0() { return cAlwaysParserRuleCall_0; }

		//Otherwise
		public RuleCall getOtherwiseParserRuleCall_1() { return cOtherwiseParserRuleCall_1; }

		//To
		public RuleCall getToParserRuleCall_2() { return cToParserRuleCall_2; }

		//From
		public RuleCall getFromParserRuleCall_3() { return cFromParserRuleCall_3; }
	}

	public class AlwaysElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Always");
		private final Assignment cKeywordAssignment = (Assignment)rule.eContents().get(1);
		private final Keyword cKeywordAlwaysKeyword_0 = (Keyword)cKeywordAssignment.eContents().get(0);
		
		//Always:
		//	keyword="always";
		public ParserRule getRule() { return rule; }

		//keyword="always"
		public Assignment getKeywordAssignment() { return cKeywordAssignment; }

		//"always"
		public Keyword getKeywordAlwaysKeyword_0() { return cKeywordAlwaysKeyword_0; }
	}

	public class OtherwiseElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Otherwise");
		private final Assignment cKeywordAssignment = (Assignment)rule.eContents().get(1);
		private final Keyword cKeywordOtherwiseKeyword_0 = (Keyword)cKeywordAssignment.eContents().get(0);
		
		//Otherwise:
		//	keyword="otherwise";
		public ParserRule getRule() { return rule; }

		//keyword="otherwise"
		public Assignment getKeywordAssignment() { return cKeywordAssignment; }

		//"otherwise"
		public Keyword getKeywordOtherwiseKeyword_0() { return cKeywordOtherwiseKeyword_0; }
	}

	public class ToElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "To");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cKeywordAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final Keyword cKeywordToKeyword_0_0 = (Keyword)cKeywordAssignment_0.eContents().get(0);
		private final Keyword cEqualsSGnKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cEventSourceAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final CrossReference cEventSourceEventSourceCrossReference_2_0 = (CrossReference)cEventSourceAssignment_2.eContents().get(0);
		private final RuleCall cEventSourceEventSourceIDTerminalRuleCall_2_0_1 = (RuleCall)cEventSourceEventSourceCrossReference_2_0.eContents().get(1);
		
		//To:
		//	keyword="to" "=" eventSource=[EventSource];
		public ParserRule getRule() { return rule; }

		//keyword="to" "=" eventSource=[EventSource]
		public Group getGroup() { return cGroup; }

		//keyword="to"
		public Assignment getKeywordAssignment_0() { return cKeywordAssignment_0; }

		//"to"
		public Keyword getKeywordToKeyword_0_0() { return cKeywordToKeyword_0_0; }

		//"="
		public Keyword getEqualsSGnKeyword_1() { return cEqualsSGnKeyword_1; }

		//eventSource=[EventSource]
		public Assignment getEventSourceAssignment_2() { return cEventSourceAssignment_2; }

		//[EventSource]
		public CrossReference getEventSourceEventSourceCrossReference_2_0() { return cEventSourceEventSourceCrossReference_2_0; }

		//ID
		public RuleCall getEventSourceEventSourceIDTerminalRuleCall_2_0_1() { return cEventSourceEventSourceIDTerminalRuleCall_2_0_1; }
	}

	public class FromElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "From");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cKeywordAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final Keyword cKeywordFromKeyword_0_0 = (Keyword)cKeywordAssignment_0.eContents().get(0);
		private final Keyword cEqualsSGnKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cEventSourceAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final CrossReference cEventSourceEventSourceCrossReference_2_0 = (CrossReference)cEventSourceAssignment_2.eContents().get(0);
		private final RuleCall cEventSourceEventSourceIDTerminalRuleCall_2_0_1 = (RuleCall)cEventSourceEventSourceCrossReference_2_0.eContents().get(1);
		
		//From:
		//	keyword="from" "=" eventSource=[EventSource];
		public ParserRule getRule() { return rule; }

		//keyword="from" "=" eventSource=[EventSource]
		public Group getGroup() { return cGroup; }

		//keyword="from"
		public Assignment getKeywordAssignment_0() { return cKeywordAssignment_0; }

		//"from"
		public Keyword getKeywordFromKeyword_0_0() { return cKeywordFromKeyword_0_0; }

		//"="
		public Keyword getEqualsSGnKeyword_1() { return cEqualsSGnKeyword_1; }

		//eventSource=[EventSource]
		public Assignment getEventSourceAssignment_2() { return cEventSourceAssignment_2; }

		//[EventSource]
		public CrossReference getEventSourceEventSourceCrossReference_2_0() { return cEventSourceEventSourceCrossReference_2_0; }

		//ID
		public RuleCall getEventSourceEventSourceIDTerminalRuleCall_2_0_1() { return cEventSourceEventSourceIDTerminalRuleCall_2_0_1; }
	}

	public class TestElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Test");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cTESTKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cOperationsAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cOperationsOperationParserRuleCall_1_0 = (RuleCall)cOperationsAssignment_1.eContents().get(0);
		private final Keyword cENDKeyword_2 = (Keyword)cGroup.eContents().get(2);
		
		//Test:
		//	"[TEST]" operations+=Operation* "[END]";
		public ParserRule getRule() { return rule; }

		//"[TEST]" operations+=Operation* "[END]"
		public Group getGroup() { return cGroup; }

		//"[TEST]"
		public Keyword getTESTKeyword_0() { return cTESTKeyword_0; }

		//operations+=Operation*
		public Assignment getOperationsAssignment_1() { return cOperationsAssignment_1; }

		//Operation
		public RuleCall getOperationsOperationParserRuleCall_1_0() { return cOperationsOperationParserRuleCall_1_0; }

		//"[END]"
		public Keyword getENDKeyword_2() { return cENDKeyword_2; }
	}
	
	
	private PDLFileElements pPDLFile;
	private DefinitionsElements pDefinitions;
	private DefineElements pDefine;
	private EventSourceElements pEventSource;
	private ArbitratorElements pArbitrator;
	private ParticipantElements pParticipant;
	private CipherElements pCipher;
	private MessageElements pMessage;
	private KeywordElements pKeyword;
	private TransactionsElements pTransactions;
	private TransactionElements pTransaction;
	private ArgumentElements pArgument;
	private OperationElements pOperation;
	private DecryptElements pDecrypt;
	private EncryptElements pEncrypt;
	private SendElements pSend;
	private PrintElements pPrint;
	private CallElements pCall;
	private ExchangeElements pExchange;
	private RedirectElements pRedirect;
	private StatesElements pStates;
	private StateElements pState;
	private GuardElements pGuard;
	private EventElements pEvent;
	private GetEventElements pGetEvent;
	private SendsEventElements pSendsEvent;
	private IsSendEventElements pIsSendEvent;
	private InitElements pInit;
	private CaseElements pCase;
	private AlwaysElements pAlways;
	private OtherwiseElements pOtherwise;
	private ToElements pTo;
	private FromElements pFrom;
	private TestElements pTest;
	
	private final GrammarProvider grammarProvider;

	private TerminalsGrammarAccess gaTerminals;

	@Inject
	public ProtocolGrammarAccess(GrammarProvider grammarProvider,
		TerminalsGrammarAccess gaTerminals) {
		this.grammarProvider = grammarProvider;
		this.gaTerminals = gaTerminals;
	}
	
	public Grammar getGrammar() {	
		return grammarProvider.getGrammar(this);
	}
	

	public TerminalsGrammarAccess getTerminalsGrammarAccess() {
		return gaTerminals;
	}

	
	//PDLFile:
	//	"[" name=ID "]" definition=Definitions transaction=Transactions state=States test=Test "[END]";
	public PDLFileElements getPDLFileAccess() {
		return (pPDLFile != null) ? pPDLFile : (pPDLFile = new PDLFileElements());
	}
	
	public ParserRule getPDLFileRule() {
		return getPDLFileAccess().getRule();
	}

	//Definitions:
	//	"[DEFINITIONS]" sources+=EventSource* cipher=Cipher message=Message "[END]";
	public DefinitionsElements getDefinitionsAccess() {
		return (pDefinitions != null) ? pDefinitions : (pDefinitions = new DefinitionsElements());
	}
	
	public ParserRule getDefinitionsRule() {
		return getDefinitionsAccess().getRule();
	}

	//// Works Like Interface
	//Define:
	//	EventSource | Cipher | Message;
	public DefineElements getDefineAccess() {
		return (pDefine != null) ? pDefine : (pDefine = new DefineElements());
	}
	
	public ParserRule getDefineRule() {
		return getDefineAccess().getRule();
	}

	//EventSource:
	//	Arbitrator | Participant;
	public EventSourceElements getEventSourceAccess() {
		return (pEventSource != null) ? pEventSource : (pEventSource = new EventSourceElements());
	}
	
	public ParserRule getEventSourceRule() {
		return getEventSourceAccess().getRule();
	}

	//Arbitrator:
	//	name=ID "=" keyword="Arbitrator";
	public ArbitratorElements getArbitratorAccess() {
		return (pArbitrator != null) ? pArbitrator : (pArbitrator = new ArbitratorElements());
	}
	
	public ParserRule getArbitratorRule() {
		return getArbitratorAccess().getRule();
	}

	//Participant:
	//	name=ID "=" keyword="Participant";
	public ParticipantElements getParticipantAccess() {
		return (pParticipant != null) ? pParticipant : (pParticipant = new ParticipantElements());
	}
	
	public ParserRule getParticipantRule() {
		return getParticipantAccess().getRule();
	}

	//Cipher:
	//	name=ID "=" keyword=("AsynchronousCipher" | "SynchronousCipher");
	public CipherElements getCipherAccess() {
		return (pCipher != null) ? pCipher : (pCipher = new CipherElements());
	}
	
	public ParserRule getCipherRule() {
		return getCipherAccess().getRule();
	}

	//Message:
	//	name=ID "=" keyword="Message";
	public MessageElements getMessageAccess() {
		return (pMessage != null) ? pMessage : (pMessage = new MessageElements());
	}
	
	public ParserRule getMessageRule() {
		return getMessageAccess().getRule();
	}

	//Keyword returns ecore::EString:
	//	"Arbitrator" | "Participant" | "Message" | "AsynchronousCipher" | "SynchronousCipher";
	public KeywordElements getKeywordAccess() {
		return (pKeyword != null) ? pKeyword : (pKeyword = new KeywordElements());
	}
	
	public ParserRule getKeywordRule() {
		return getKeywordAccess().getRule();
	}

	//Transactions:
	//	"[TRANSACTIONS]" transactions+=Transaction* "[END]";
	public TransactionsElements getTransactionsAccess() {
		return (pTransactions != null) ? pTransactions : (pTransactions = new TransactionsElements());
	}
	
	public ParserRule getTransactionsRule() {
		return getTransactionsAccess().getRule();
	}

	//Transaction:
	//	"TRANSACTION" name=ID "(" arguments+=Argument* ")" "[BEGIN]" operations+=Operation* "[END]";
	public TransactionElements getTransactionAccess() {
		return (pTransaction != null) ? pTransaction : (pTransaction = new TransactionElements());
	}
	
	public ParserRule getTransactionRule() {
		return getTransactionAccess().getRule();
	}

	//Argument:
	//	keyword=Keyword name=ID;
	public ArgumentElements getArgumentAccess() {
		return (pArgument != null) ? pArgument : (pArgument = new ArgumentElements());
	}
	
	public ParserRule getArgumentRule() {
		return getArgumentAccess().getRule();
	}

	//Operation:
	//	Decrypt | Encrypt | Send | Print | Call | Exchange | Redirect;
	public OperationElements getOperationAccess() {
		return (pOperation != null) ? pOperation : (pOperation = new OperationElements());
	}
	
	public ParserRule getOperationRule() {
		return getOperationAccess().getRule();
	}

	//Decrypt:
	//	"decrypt" message=ID "for" participant=[Participant];
	public DecryptElements getDecryptAccess() {
		return (pDecrypt != null) ? pDecrypt : (pDecrypt = new DecryptElements());
	}
	
	public ParserRule getDecryptRule() {
		return getDecryptAccess().getRule();
	}

	//Encrypt:
	//	"encrypt" message=ID "for" participant=[Participant];
	public EncryptElements getEncryptAccess() {
		return (pEncrypt != null) ? pEncrypt : (pEncrypt = new EncryptElements());
	}
	
	public ParserRule getEncryptRule() {
		return getEncryptAccess().getRule();
	}

	//Send:
	//	message=ID "::" source=[EventSource] "->" destination=[EventSource];
	public SendElements getSendAccess() {
		return (pSend != null) ? pSend : (pSend = new SendElements());
	}
	
	public ParserRule getSendRule() {
		return getSendAccess().getRule();
	}

	//Print:
	//	"print" message=ID;
	public PrintElements getPrintAccess() {
		return (pPrint != null) ? pPrint : (pPrint = new PrintElements());
	}
	
	public ParserRule getPrintRule() {
		return getPrintAccess().getRule();
	}

	//Call:
	//	"CALL" transactionName=[Transaction] "(" args+=[Define]* ")";
	public CallElements getCallAccess() {
		return (pCall != null) ? pCall : (pCall = new CallElements());
	}
	
	public ParserRule getCallRule() {
		return getCallAccess().getRule();
	}

	//Exchange:
	//	source=[EventSource] "exchange" destination=[EventSource];
	public ExchangeElements getExchangeAccess() {
		return (pExchange != null) ? pExchange : (pExchange = new ExchangeElements());
	}
	
	public ParserRule getExchangeRule() {
		return getExchangeAccess().getRule();
	}

	//Redirect:
	//	message=ID "redirect" destination=[EventSource];
	public RedirectElements getRedirectAccess() {
		return (pRedirect != null) ? pRedirect : (pRedirect = new RedirectElements());
	}
	
	public ParserRule getRedirectRule() {
		return getRedirectAccess().getRule();
	}

	//States:
	//	"[STATES]" states+=State* "[END]";
	public StatesElements getStatesAccess() {
		return (pStates != null) ? pStates : (pStates = new StatesElements());
	}
	
	public ParserRule getStatesRule() {
		return getStatesAccess().getRule();
	}

	//State:
	//	"STATE" name=ID "(" event=Event ")" "[BEGIN]" guards+=Guard* "[END]";
	public StateElements getStateAccess() {
		return (pState != null) ? pState : (pState = new StateElements());
	}
	
	public ParserRule getStateRule() {
		return getStateAccess().getRule();
	}

	//Guard:
	//	"|" casem=Case "=>" operation=Operation;
	public GuardElements getGuardAccess() {
		return (pGuard != null) ? pGuard : (pGuard = new GuardElements());
	}
	
	public ParserRule getGuardRule() {
		return getGuardAccess().getRule();
	}

	//Event:
	//	GetEvent | IsSendEvent | Init | SendsEvent;
	public EventElements getEventAccess() {
		return (pEvent != null) ? pEvent : (pEvent = new EventElements());
	}
	
	public ParserRule getEventRule() {
		return getEventAccess().getRule();
	}

	//GetEvent:
	//	who=[Define] "GET" message=[Message];
	public GetEventElements getGetEventAccess() {
		return (pGetEvent != null) ? pGetEvent : (pGetEvent = new GetEventElements());
	}
	
	public ParserRule getGetEventRule() {
		return getGetEventAccess().getRule();
	}

	//SendsEvent:
	//	who=[Define] "SENDS" message=[Message];
	public SendsEventElements getSendsEventAccess() {
		return (pSendsEvent != null) ? pSendsEvent : (pSendsEvent = new SendsEventElements());
	}
	
	public ParserRule getSendsEventRule() {
		return getSendsEventAccess().getRule();
	}

	//IsSendEvent:
	//	message=[Message] "IS_SEND";
	public IsSendEventElements getIsSendEventAccess() {
		return (pIsSendEvent != null) ? pIsSendEvent : (pIsSendEvent = new IsSendEventElements());
	}
	
	public ParserRule getIsSendEventRule() {
		return getIsSendEventAccess().getRule();
	}

	//Init:
	//	keyword="INIT";
	public InitElements getInitAccess() {
		return (pInit != null) ? pInit : (pInit = new InitElements());
	}
	
	public ParserRule getInitRule() {
		return getInitAccess().getRule();
	}

	//Case:
	//	Always | Otherwise | To | From;
	public CaseElements getCaseAccess() {
		return (pCase != null) ? pCase : (pCase = new CaseElements());
	}
	
	public ParserRule getCaseRule() {
		return getCaseAccess().getRule();
	}

	//Always:
	//	keyword="always";
	public AlwaysElements getAlwaysAccess() {
		return (pAlways != null) ? pAlways : (pAlways = new AlwaysElements());
	}
	
	public ParserRule getAlwaysRule() {
		return getAlwaysAccess().getRule();
	}

	//Otherwise:
	//	keyword="otherwise";
	public OtherwiseElements getOtherwiseAccess() {
		return (pOtherwise != null) ? pOtherwise : (pOtherwise = new OtherwiseElements());
	}
	
	public ParserRule getOtherwiseRule() {
		return getOtherwiseAccess().getRule();
	}

	//To:
	//	keyword="to" "=" eventSource=[EventSource];
	public ToElements getToAccess() {
		return (pTo != null) ? pTo : (pTo = new ToElements());
	}
	
	public ParserRule getToRule() {
		return getToAccess().getRule();
	}

	//From:
	//	keyword="from" "=" eventSource=[EventSource];
	public FromElements getFromAccess() {
		return (pFrom != null) ? pFrom : (pFrom = new FromElements());
	}
	
	public ParserRule getFromRule() {
		return getFromAccess().getRule();
	}

	//Test:
	//	"[TEST]" operations+=Operation* "[END]";
	public TestElements getTestAccess() {
		return (pTest != null) ? pTest : (pTest = new TestElements());
	}
	
	public ParserRule getTestRule() {
		return getTestAccess().getRule();
	}

	//terminal ID:
	//	"^"? ("a".."z" | "A".."Z" | "_") ("a".."z" | "A".."Z" | "_" | "0".."9")*;
	public TerminalRule getIDRule() {
		return gaTerminals.getIDRule();
	} 

	//terminal INT returns ecore::EInt:
	//	"0".."9"+;
	public TerminalRule getINTRule() {
		return gaTerminals.getINTRule();
	} 

	//terminal STRING:
	//	"\"" ("\\" ("b" | "t" | "n" | "f" | "r" | "\"" | "\'" | "\\") | !("\\" | "\""))* "\"" | "\'" ("\\" ("b" | "t" | "n" |
	//	"f" | "r" | "\"" | "\'" | "\\") | !("\\" | "\'"))* "\'";
	public TerminalRule getSTRINGRule() {
		return gaTerminals.getSTRINGRule();
	} 

	//terminal ML_COMMENT:
	//	"/ *"->"* /";
	public TerminalRule getML_COMMENTRule() {
		return gaTerminals.getML_COMMENTRule();
	} 

	//terminal SL_COMMENT:
	//	"//" !("\n" | "\r")* ("\r"? "\n")?;
	public TerminalRule getSL_COMMENTRule() {
		return gaTerminals.getSL_COMMENTRule();
	} 

	//terminal WS:
	//	(" " | "\t" | "\r" | "\n")+;
	public TerminalRule getWSRule() {
		return gaTerminals.getWSRule();
	} 

	//terminal ANY_OTHER:
	//	.;
	public TerminalRule getANY_OTHERRule() {
		return gaTerminals.getANY_OTHERRule();
	} 
}
