/*
* generated by Xtext
*/
package org.xtext.senior.project.ui.contentassist;

import org.xtext.senior.project.ui.contentassist.AbstractProtocolProposalProvider;
/**
 * see http://www.eclipse.org/Xtext/documentation/latest/xtext.html#contentAssist on how to customize content assistant
 */
public class ProtocolProposalProvider extends AbstractProtocolProposalProvider {

}
