/*
* generated by Xtext
*/
package org.xtext.senior.project.ui.outline;

import org.eclipse.xtext.ui.editor.outline.transformer.AbstractDeclarativeSemanticModelTransformer;

/**
 * customization of the default outline structure
 * 
 */
public class ProtocolTransformer extends AbstractDeclarativeSemanticModelTransformer {
	
}
